# Generated by Django 6.0.3 on 2026-03-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assessmentsession_codingsubmission_cvanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='enrolled_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
