# Generated by Django 6.0.2 on 2026-03-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_result_coding_score_result_skill_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='proctoring_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='structure_instructions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
