# Generated by Django 6.0.2 on 2026-03-14 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_assessment_proctoring_rules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('extracted_text', models.TextField()),
                ('detected_skills', models.JSONField(default=list)),
                ('qa_history', models.JSONField(default=list)),
                ('overall_score', models.IntegerField(default=0)),
                ('communication_score', models.IntegerField(default=0)),
                ('technical_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('feedback_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='initialized', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
