# Generated by Django 6.0.2 on 2026-03-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_aiinterviewsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewsession',
            name='answer_quality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='improvements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='problem_solving_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
