# Generated by Django 6.0.2 on 2026-03-26 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aiinterviewsession_answer_quality_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('skill_test', 'Skill Test'), ('ai_interview', 'AI Interview')], max_length=20)),
                ('overall_score', models.FloatField(default=0.0)),
                ('skill_level', models.CharField(default='Beginner', max_length=50)),
                ('skill_breakdown', models.JSONField(default=dict)),
                ('identified_gaps', models.JSONField(default=list)),
                ('roadmap', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.result')),
                ('interview_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.aiinterviewsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Skill Gap Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
