# Generated by Django 6.0.2 on 2026-04-18 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_testassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewsession',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.assessment'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('mcq', 'MCQ Exam'), ('interview', 'AI Interview')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='interview_category',
            field=models.CharField(blank=True, choices=[('hr', 'HR Interview'), ('technical', 'Technical Interview')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aiinterviewsession',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aiinterviewsession',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
