# Generated by Django 6.0.2 on 2026-04-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_aiinterviewsession_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringviolation',
            name='interview_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='api.aiinterviewsession'),
        ),
        migrations.AlterField(
            model_name='proctoringviolation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='api.assessmentsession'),
        ),
    ]
