# Generated by Django 6.0.2 on 2026-04-18 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_proctoringviolation_interview_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_name', models.CharField(blank=True, max_length=150)),
                ('test_type', models.CharField(choices=[('ai_skill', 'AI Skill Test'), ('ai_interview', 'AI Interview'), ('coding', 'Coding Test'), ('confidence', 'Confidence Analyzer')], max_length=20)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('custom_message', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('opened', 'Opened'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
